apiVersion: v1
kind: Pod
metadata:
  name: afknife
  namespace: default
spec:
  containers:
  - image: akiffeyzioglu/afknife:v1
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
    imagePullPolicy: Always
    name: afknife
  restartPolicy: Always